name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.deno
          ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}

    - name: Format check
      run: deno fmt --check

    - name: Lint
      run: deno lint

    - name: Run tests
      run: deno task test
      env:
        DENO_ENV: test

    - name: Type check
      run: deno check src/**/*.ts